import { swatchTokens } from "@openuidev/react-ui/ThemeProvider";

const FONT_FAMILY = 'var(--font-inter), "Inter", "Segoe UI", Arial, sans-serif';

export const fontOverrides = {
  fontBody: FONT_FAMILY,
  fontHeading: FONT_FAMILY,
  fontLabel: FONT_FAMILY,
  fontNumbers: FONT_FAMILY,
};

const ALIASES: Record<string, string> = {
  "--background": "var(--openui-background)",
  "--foreground": "var(--openui-foreground)",
  "--openui-background": "var(--background)",
  "--openui-foreground": "var(--foreground)",
  "--popover-background": "var(--openui-popover-background)",
  "--sunk-light": "var(--openui-sunk-light)",
  "--sunk": "var(--openui-sunk)",
  "--sunk-deep": "var(--openui-sunk-deep)",
  "--elevated-light": "var(--openui-elevated-light)",
  "--elevated": "var(--openui-elevated)",
  "--elevated-strong": "var(--openui-elevated-strong)",
  "--elevated-intense": "var(--openui-elevated-intense)",
  "--overlay": "var(--openui-overlay)",
  "--highlight-subtle": "var(--openui-highlight-subtle)",
  "--highlight": "var(--openui-highlight)",
  "--highlight-strong": "var(--openui-highlight-strong)",
  "--highlight-intense": "var(--openui-highlight-intense)",
  "--inverted-background": "var(--openui-inverted-background)",
  "--info-background": "var(--openui-info-background)",
  "--success-background": "var(--openui-success-background)",
  "--alert-background": "var(--openui-alert-background)",
  "--danger-background": "var(--openui-danger-background)",
  "--purple-background": "var(--openui-purple-background)",
  "--pink-background": "var(--openui-pink-background)",
  "--text-neutral-primary": "var(--openui-text-neutral-primary)",
  "--text-neutral-secondary": "var(--openui-text-neutral-secondary)",
  "--text-neutral-tertiary": "var(--openui-text-neutral-tertiary)",
  "--text-neutral-link": "var(--openui-text-neutral-link)",
  "--text-brand": "var(--openui-text-brand)",
  "--text-white": "var(--openui-text-white)",
  "--text-black": "var(--openui-text-black)",
  "--text-accent-primary": "var(--openui-text-accent-primary)",
  "--text-accent-secondary": "var(--openui-text-accent-secondary)",
  "--text-accent-tertiary": "var(--openui-text-accent-tertiary)",
  "--text-success-primary": "var(--openui-text-success-primary)",
  "--text-success-inverted": "var(--openui-text-success-inverted)",
  "--text-alert-primary": "var(--openui-text-alert-primary)",
  "--text-alert-inverted": "var(--openui-text-alert-inverted)",
  "--text-danger-primary": "var(--openui-text-danger-primary)",
  "--text-danger-secondary": "var(--openui-text-danger-secondary)",
  "--text-danger-tertiary": "var(--openui-text-danger-tertiary)",
  "--text-danger-inverted-primary": "var(--openui-text-danger-inverted-primary)",
  "--text-danger-inverted-secondary": "var(--openui-text-danger-inverted-secondary)",
  "--text-danger-inverted-tertiary": "var(--openui-text-danger-inverted-tertiary)",
  "--text-info-primary": "var(--openui-text-info-primary)",
  "--text-info-inverted": "var(--openui-text-info-inverted)",
  "--text-pink-primary": "var(--openui-text-pink-primary)",
  "--text-pink-inverted": "var(--openui-text-pink-inverted)",
  "--text-purple-primary": "var(--openui-text-purple-primary)",
  "--text-purple-inverted": "var(--openui-text-purple-inverted)",
  "--interactive-accent-default": "var(--openui-interactive-accent-default)",
  "--interactive-brand-default": "var(--openui-interactive-accent-default)",
  "--interactive-accent-hover": "var(--openui-interactive-accent-hover)",
  "--interactive-accent-disabled": "var(--openui-interactive-accent-disabled)",
  "--interactive-accent-pressed": "var(--openui-interactive-accent-pressed)",
  "--interactive-destructive-default": "var(--openui-interactive-destructive-default)",
  "--interactive-destructive-hover": "var(--openui-interactive-destructive-hover)",
  "--interactive-destructive-disabled": "var(--openui-interactive-destructive-disabled)",
  "--interactive-destructive-pressed": "var(--openui-interactive-destructive-pressed)",
  "--interactive-destructive-accent-default":
    "var(--openui-interactive-destructive-accent-default)",
  "--interactive-destructive-accent-hover": "var(--openui-interactive-destructive-accent-hover)",
  "--interactive-destructive-accent-pressed":
    "var(--openui-interactive-destructive-accent-pressed)",
  "--interactive-destructive-accent-disabled":
    "var(--openui-interactive-destructive-accent-disabled)",
  "--border-default": "var(--openui-border-default)",
  "--border-interactive": "var(--openui-border-interactive)",
  "--border-interactive-emphasis": "var(--openui-border-interactive-emphasis)",
  "--border-interactive-selected": "var(--openui-border-interactive-selected)",
  "--border-interactive-elements-selected": "var(--openui-border-interactive-selected)",
  "--border-accent": "var(--openui-border-accent)",
  "--border-accent-emphasis": "var(--openui-border-accent-emphasis)",
  "--border-info": "var(--openui-border-info)",
  "--border-info-emphasis": "var(--openui-border-info-emphasis)",
  "--border-alert": "var(--openui-border-alert)",
  "--border-alert-emphasis": "var(--openui-border-alert-emphasis)",
  "--border-success": "var(--openui-border-success)",
  "--border-success-emphasis": "var(--openui-border-success-emphasis)",
  "--border-danger": "var(--openui-border-danger)",
  "--border-danger-emphasis": "var(--openui-border-danger-emphasis)",
  "--space-000": "var(--openui-space-000)",
  "--space-3xs": "var(--openui-space-3xs)",
  "--space-2xs": "var(--openui-space-2xs)",
  "--space-xs": "var(--openui-space-xs)",
  "--space-s": "var(--openui-space-s)",
  "--space-s-m": "var(--openui-space-s-m)",
  "--space-m": "var(--openui-space-m)",
  "--space-m-l": "var(--openui-space-m-l)",
  "--space-l": "var(--openui-space-l)",
  "--space-xl": "var(--openui-space-xl)",
  "--space-2xl": "var(--openui-space-2xl)",
  "--space-3xl": "var(--openui-space-3xl)",
  "--space-0": "var(--space-000)",
  "--space-1": "var(--space-3xs)",
  "--space-2": "var(--space-2xs)",
  "--space-3": "var(--space-xs)",
  "--space-4": "var(--space-s)",
  "--space-5": "var(--space-s-m)",
  "--space-6": "var(--space-m)",
  "--space-8": "var(--space-m-l)",
  "--space-10": "var(--space-l)",
  "--space-12": "var(--space-xl)",
  "--space-16": "var(--space-2xl)",
  "--radius-none": "var(--openui-radius-none)",
  "--radius-3xs": "var(--openui-radius-3xs)",
  "--radius-2xs": "var(--openui-radius-2xs)",
  "--radius-xs": "var(--openui-radius-xs)",
  "--radius-s": "var(--openui-radius-s)",
  "--radius-m": "var(--openui-radius-m)",
  "--radius-l": "var(--openui-radius-l)",
  "--radius-xl": "var(--openui-radius-xl)",
  "--radius-2xl": "var(--openui-radius-2xl)",
  "--radius-3xl": "var(--openui-radius-3xl)",
  "--radius-4xl": "var(--openui-radius-4xl)",
  "--radius-5xl": "var(--openui-radius-5xl)",
  "--radius-6xl": "var(--openui-radius-6xl)",
  "--radius-7xl": "var(--openui-radius-7xl)",
  "--radius-8xl": "var(--openui-radius-8xl)",
  "--radius-9xl": "var(--openui-radius-9xl)",
  "--radius-full": "var(--openui-radius-full)",
  "--shadow-none": "var(--openui-shadow-0)",
  "--shadow-s": "var(--openui-shadow-s)",
  "--shadow-m": "var(--openui-shadow-m)",
  "--shadow-l": "var(--openui-shadow-l)",
  "--shadow-xl": "var(--openui-shadow-xl)",
  "--shadow-2xl": "var(--openui-shadow-2xl)",
  "--shadow-3xl": "var(--openui-shadow-3xl)",
  "--font-body": "var(--openui-font-body)",
  "--font-code": "var(--openui-font-code)",
  "--font-heading": "var(--openui-font-heading)",
  "--font-label": "var(--openui-font-label)",
  "--font-numbers": "var(--openui-font-numbers)",
  "--text-body-xs": "var(--openui-text-body-xs)",
  "--text-body-xs-letter-spacing": "var(--openui-text-body-xs-letter-spacing)",
  "--text-body-xs-heavy": "var(--openui-text-body-xs-heavy)",
  "--text-body-xs-heavy-letter-spacing": "var(--openui-text-body-xs-heavy-letter-spacing)",
  "--text-body-sm": "var(--openui-text-body-sm)",
  "--text-body-sm-letter-spacing": "var(--openui-text-body-sm-letter-spacing)",
  "--text-body-sm-heavy": "var(--openui-text-body-sm-heavy)",
  "--text-body-sm-heavy-letter-spacing": "var(--openui-text-body-sm-heavy-letter-spacing)",
  "--text-body-default": "var(--openui-text-body-default)",
  "--text-body-default-letter-spacing": "var(--openui-text-body-default-letter-spacing)",
  "--text-body-default-heavy": "var(--openui-text-body-default-heavy)",
  "--text-body-default-heavy-letter-spacing":
    "var(--openui-text-body-default-heavy-letter-spacing)",
  "--text-body-lg": "var(--openui-text-body-lg)",
  "--text-body-lg-letter-spacing": "var(--openui-text-body-lg-letter-spacing)",
  "--text-body-lg-heavy": "var(--openui-text-body-lg-heavy)",
  "--text-body-lg-heavy-letter-spacing": "var(--openui-text-body-lg-heavy-letter-spacing)",
  "--text-heading-xs": "var(--openui-text-heading-xs)",
  "--text-heading-xs-letter-spacing": "var(--openui-text-heading-xs-letter-spacing)",
  "--text-heading-sm": "var(--openui-text-heading-sm)",
  "--text-heading-sm-letter-spacing": "var(--openui-text-heading-sm-letter-spacing)",
  "--text-heading-md": "var(--openui-text-heading-md)",
  "--text-heading-md-letter-spacing": "var(--openui-text-heading-md-letter-spacing)",
  "--text-heading-lg": "var(--openui-text-heading-lg)",
  "--text-heading-lg-letter-spacing": "var(--openui-text-heading-lg-letter-spacing)",
  "--text-heading-xl": "var(--openui-text-heading-xl)",
  "--text-heading-xl-letter-spacing": "var(--openui-text-heading-xl-letter-spacing)",
  "--text-label-xs": "var(--openui-text-label-xs)",
  "--text-label-xs-letter-spacing": "var(--openui-text-label-xs-letter-spacing)",
  "--text-label-xs-heavy": "var(--openui-text-label-xs-heavy)",
  "--text-label-xs-heavy-letter-spacing": "var(--openui-text-label-xs-heavy-letter-spacing)",
  "--text-label-sm": "var(--openui-text-label-sm)",
  "--text-label-sm-letter-spacing": "var(--openui-text-label-sm-letter-spacing)",
  "--text-label-sm-heavy": "var(--openui-text-label-sm-heavy)",
  "--text-label-sm-heavy-letter-spacing": "var(--openui-text-label-sm-heavy-letter-spacing)",
  "--text-label-default": "var(--openui-text-label-default)",
  "--text-label-default-letter-spacing": "var(--openui-text-label-default-letter-spacing)",
  "--text-label-default-heavy": "var(--openui-text-label-default-heavy)",
  "--text-label-default-heavy-letter-spacing":
    "var(--openui-text-label-default-heavy-letter-spacing)",
  "--text-label-lg": "var(--openui-text-label-lg)",
  "--text-label-lg-letter-spacing": "var(--openui-text-label-lg-letter-spacing)",
  "--text-label-lg-heavy": "var(--openui-text-label-lg-heavy)",
  "--text-label-lg-heavy-letter-spacing": "var(--openui-text-label-lg-heavy-letter-spacing)",
  "--text-numbers-xs": "var(--openui-text-numbers-xs)",
  "--text-numbers-xs-letter-spacing": "var(--openui-text-numbers-xs-letter-spacing)",
  "--text-numbers-xs-heavy": "var(--openui-text-numbers-xs-heavy)",
  "--text-numbers-xs-heavy-letter-spacing": "var(--openui-text-numbers-xs-heavy-letter-spacing)",
  "--text-numbers-sm": "var(--openui-text-numbers-sm)",
  "--text-numbers-sm-letter-spacing": "var(--openui-text-numbers-sm-letter-spacing)",
  "--text-numbers-sm-heavy": "var(--openui-text-numbers-sm-heavy)",
  "--text-numbers-sm-heavy-letter-spacing": "var(--openui-text-numbers-sm-heavy-letter-spacing)",
  "--text-numbers-default": "var(--openui-text-numbers-default)",
  "--text-numbers-default-letter-spacing": "var(--openui-text-numbers-default-letter-spacing)",
  "--text-numbers-default-heavy": "var(--openui-text-numbers-default-heavy)",
  "--text-numbers-default-heavy-letter-spacing":
    "var(--openui-text-numbers-default-heavy-letter-spacing)",
  "--text-numbers-lg": "var(--openui-text-numbers-lg)",
  "--text-numbers-lg-letter-spacing": "var(--openui-text-numbers-lg-letter-spacing)",
  "--text-numbers-lg-heavy": "var(--openui-text-numbers-lg-heavy)",
  "--text-numbers-lg-heavy-letter-spacing": "var(--openui-text-numbers-lg-heavy-letter-spacing)",
  "--text-code-sm": "var(--openui-text-code-sm)",
  "--text-code-sm-letter-spacing": "var(--openui-text-code-sm-letter-spacing)",
  "--text-code-sm-heavy": "var(--openui-text-code-sm-heavy)",
  "--text-code-sm-heavy-letter-spacing": "var(--openui-text-code-sm-heavy-letter-spacing)",
  "--text-code-default": "var(--openui-text-code-default)",
  "--text-code-default-letter-spacing": "var(--openui-text-code-default-letter-spacing)",
  "--text-code-default-heavy": "var(--openui-text-code-default-heavy)",
  "--text-code-default-heavy-letter-spacing":
    "var(--openui-text-code-default-heavy-letter-spacing)",
  "--motion-duration-fast": "120ms",
  "--motion-duration-default": "200ms",
  "--motion-duration-slow": "320ms",
  "--motion-duration-slower": "480ms",
  "--motion-ease-standard": "cubic-bezier(0.2, 0, 0, 1)",
  "--motion-ease-emphasized": "cubic-bezier(0.2, 0, 0, 1.2)",
};

export const legacyVarCss = Object.entries(ALIASES)
  .map(([name, value]) => `${name}: ${value};`)
  .join("\n");

export const swatchVarCss = Object.entries(swatchTokens)
  .map(([name, value]) => `--swatch-${name}: ${value};`)
  .join("\n");
